<a href="https://colab.research.google.com/github/shub19/Project/blob/master/bootcamp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import torch

### 10 minute NumPy Blitz
Numpy is a super-useful array-processing package in python. Together with Scipy, it enables numerical and scientific computing in Python's workspace. It is intuitive, fast, and covers almost everything we can think of doing with with n-dimentional arrays

The fundamental object of numpy is its array object:

In [2]:
# This is a normal array (or 'list' as they call it in python)
a = [1,2,3,5]
print(type(a))

# This is the same array converted to a numpy array
b = np.array(a)
print(b)
print(type(b))


<class 'list'>
[1 2 3 5]
<class 'numpy.ndarray'>


In [22]:
a=[1,2,3,4,5,6]
b=torch.tensor(a)
print(a,b)
print(b.size())
b=b.reshape(2,3)
print(b)
z=np.zeros((3,4,2))
print(z)
q=torch.tensor(z)
print(q,q.size())
q=q.reshape((4,3,2))
print(q.size())
a=[1,2,3,4,5,6,7,8,9,10,11,12]
a=torch.tensor(a)
a=a.reshape(2,3,2)
print(a)

[1, 2, 3, 4, 5, 6] tensor([1, 2, 3, 4, 5, 6])
torch.Size([6])
tensor([[1, 2, 3],
        [4, 5, 6]])
[[[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]]
tensor([[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]], dtype=torch.float64) torch.Size([3, 4, 2])
torch.Size([4, 3, 2])
tensor([[[ 1,  2],
         [ 3,  4],
         [ 5,  6]],

        [[ 7,  8],
         [ 9, 10],
         [11, 12]]])


In [3]:
# Let's define a multi-dimensional array
a = [[1,2],[2,4],[4,1],[2,5]]

b = np.array(a)
print(b)
print(type(b))

[[1 2]
 [2 4]
 [4 1]
 [2 5]]
<class 'numpy.ndarray'>


In [4]:
# To know the shape of a numpy array, get the shape variable
c = b.shape
print(c)
print(type(c))

# the shape of a numpy array is a tuple consisting of the number of dimensions.
print(b.shape[0], b.shape[1])

(4, 2)
<class 'tuple'>
4 2


In [5]:
# We can initialize a numpy array in other ways too:
a = np.zeros((3,4))
print(a)
print(a.shape)

b = np.ones((3,4))
print(b)
print(b.shape)

c = np.random.random((3,4))
print(c)
print(c.shape)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
(3, 4)
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
(3, 4)
[[0.02296955 0.92983487 0.47058818 0.86842185]
 [0.95298597 0.72941063 0.6862208  0.84954634]
 [0.43992213 0.91993525 0.62966499 0.72605014]]
(3, 4)


In [6]:
# We can reshape the numpy arrays using reshape 
d = c.reshape(3,2,2)
print(c)
print(d)

[[0.02296955 0.92983487 0.47058818 0.86842185]
 [0.95298597 0.72941063 0.6862208  0.84954634]
 [0.43992213 0.91993525 0.62966499 0.72605014]]
[[[0.02296955 0.92983487]
  [0.47058818 0.86842185]]

 [[0.95298597 0.72941063]
  [0.6862208  0.84954634]]

 [[0.43992213 0.91993525]
  [0.62966499 0.72605014]]]


In [7]:
# We can also perform aggregation operators in numpy
sum_d = d.sum()
print(sum_d)
print(d.mean())
print(d.var())
print('\n')

# We can also aggregate along a specific dimension
sum_d_0 = d.sum(0)
print(sum_d_0)

sum_d_1 = d.sum(1)
print(sum_d_1)

# Notice the shapes after summing in a particular dimension
# Aggregation operation marginalizes across that dimension
# So a 3x2x2 shaped array summed in dimesion 0 becomes 2x2 shaped

8.225550704002357
0.6854625586668631
0.06655937094501237


[[1.41587765 2.57918076]
 [1.78647397 2.44401833]]
[[0.49355773 1.79825673]
 [1.63920677 1.57895697]
 [1.06958712 1.64598539]]


In [8]:
# We can save and load numpy arrays in binary format using this:
np.save('save_d.npy', d)
e = np.load('save_d.npy')
print(e)

[[[0.02296955 0.92983487]
  [0.47058818 0.86842185]]

 [[0.95298597 0.72941063]
  [0.6862208  0.84954634]]

 [[0.43992213 0.91993525]
  [0.62966499 0.72605014]]]


### 10 minute PyTorch intro
PyTorch is a general purpose deep-learning python library. Just like NumPy has numpy arrays, at the core of PyTorch are pytorch tensors. On surface (and for a 10 minute blitz), they operate in a similar way as numpy arrays. Let's see how:

In [9]:
a = [1,2,3,4,5]
b = torch.tensor(a)
print(b)
print(type(b))

tensor([1, 2, 3, 4, 5])
<class 'torch.Tensor'>


In [10]:
# We can also convert a numpy array into pytorch variable
f = torch.tensor(e)
print(f)

# now deprecated, but can be seen in old codes
g = torch.from_numpy(e) 
print(g)

tensor([[[0.0230, 0.9298],
         [0.4706, 0.8684]],

        [[0.9530, 0.7294],
         [0.6862, 0.8495]],

        [[0.4399, 0.9199],
         [0.6297, 0.7261]]], dtype=torch.float64)
tensor([[[0.0230, 0.9298],
         [0.4706, 0.8684]],

        [[0.9530, 0.7294],
         [0.6862, 0.8495]],

        [[0.4399, 0.9199],
         [0.6297, 0.7261]]], dtype=torch.float64)


In [11]:
# Just like numpy, tensors have shapes (also called sizes)
print(g.shape)
print(g.size())

# And we can reshape the tensors
h = g.reshape(3,4)
print(h)

torch.Size([3, 2, 2])
torch.Size([3, 2, 2])
tensor([[0.0230, 0.9298, 0.4706, 0.8684],
        [0.9530, 0.7294, 0.6862, 0.8495],
        [0.4399, 0.9199, 0.6297, 0.7261]], dtype=torch.float64)


In [12]:
# We can also save and load torch tensors
torch.save(h, 'save_torch.pt')
i = torch.load('save_torch.pt')
print(i)

tensor([[0.0230, 0.9298, 0.4706, 0.8684],
        [0.9530, 0.7294, 0.6862, 0.8495],
        [0.4399, 0.9199, 0.6297, 0.7261]], dtype=torch.float64)


With this brief intro to pytorch and numpy, we'll begin looking at the problem set